name: label-mutex
branding:
  icon: bookmark
  color: gray-dark
inputs:
  GITHUB_TOKEN:
    description: Github token to use to create label
    required: true
  label:
    description: The name of the label
    required: true
runs:
  using: docker
  image: Dockerfile